### ISSUE TITLE
Uncaught SyntaxError: Unexpected token import

### ISSUE THREAD

**Issue by xiaoyi-wang** [wangdahoo/vue-scroller#1]
按照你的step来run ，报错~
`Uncaught SyntaxError: Unexpected token import
    at Object.<anonymous> (http://localhost:8080/app.js:1260:2)
    at __webpack_require__ (http://localhost:8080/app.js:556:30)
    at fn (http://localhost:8080/app.js:87:20)
    at eval (eval at <anonymous> (http://localhost:8080/app.js:876:2), <anonymous>:7:20)
    at Object.<anonymous> (http://localhost:8080/app.js:876:2)
    at __webpack_require__ (http://localhost:8080/app.js:556:30)
    at fn (http://localhost:8080/app.js:87:20)
    at eval (eval at <anonymous> (http://localhost:8080/app.js:1080:2), <anonymous>:7:19)
    at Object.<anonymous> (http://localhost:8080/app.js:1080:2)
    at __webpack_require__ (http://localhost:8080/app.js:556:30)`

**Comment by wangdahoo** [comment]
刚重试了readme中步骤，可以正常跑。请重试或查阅项目demo目录中的代码。
